In [17]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[13  4  1  6  3  6  7 14]


In [18]:
## Check element of array b is greater than 10 or not
print(b > 10)

[ True False False False False False False  True]


In [19]:
bool_arr = b > 10
print(bool_arr)

new_arr = b[bool_arr]
print(new_arr)

[ True False False False False False False  True]
[13 14]


In [20]:
new_arr = b[b > 10]
print(new_arr)

[13 14]


In [21]:
new_arr = b[(b > 10) & (b < 18)]
print(new_arr)

[13 14]


In [22]:
print(b)
c = b
print(c)
c[:3] = 19
c

[13  4  1  6  3  6  7 14]
[13  4  1  6  3  6  7 14]


array([19, 19, 19,  6,  3,  6,  7, 14])

In [23]:
c[c>15] = 100
print(c)

[100 100 100   6   3   6   7  14]


### np.where()

In [24]:
print(b)

[100 100 100   6   3   6   7  14]


In [25]:
print(b[b == 100])

[100 100 100]


In [26]:
idx = np.where(b == 100)
idx

(array([0, 1, 2]),)

In [27]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   6   3   6   7  14]


In [28]:
### Print a[i] only for b[i] == 100
idx = np.where(b == 100)
print(idx)
print(a[idx])

(array([0, 1, 2]),)
['t' 'b' 'r']


In [30]:
a = np.array([1,2,0,0,4,0])
print(a)

[1 2 0 0 4 0]


In [32]:
print(np.where(a > 0))
print(np.where(a))

(array([0, 1, 4]),)
(array([0, 1, 4]),)


In [38]:
a = np.array([1,2,3,5,7,11,13,15,17,19])
print(np.where(a%3))

(array([0, 1, 3, 4, 5, 6, 8, 9]),)


In [39]:
c = a
print(a)
print(c)
c[c%2 > 0] = -1
print(c)

[ 1  2  3  5  7 11 13 15 17 19]
[ 1  2  3  5  7 11 13 15 17 19]
[-1  2 -1 -1 -1 -1 -1 -1 -1 -1]


In [45]:
c = np.arange(1,11)
print(c)
c[c%2 > 0] = -1
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [46]:
c = np.array([11,2,13,4,15,6,27,8,19])
print(c)
c[np.argmax(c)] = 0
print(c)

[11  2 13  4 15  6 27  8 19]
[11  2 13  4 15  6  0  8 19]


In [52]:
a = np.arange(1,11)
c = a[(a<3) | (a>8)]
print(c)

[ 1  2  9 10]


In [69]:
ht = np.random.randint(100,200,20)
print(ht)
cc = np.random.randint(64, 90, 20)
name = [chr(i) for i in cc]
print(name)
print(cc[np.where(ht > 155)])
print(ht[ht>155])

[189 122 144 159 122 142 154 142 159 143 188 103 154 103 101 197 105 197
 100 116]
['I', 'S', 'S', 'S', 'I', 'L', 'U', 'J', 'W', 'B', 'S', '@', 'D', 'Q', 'O', 'U', 'P', 'Q', 'X', 'C']
[73 83 87 83 85 81]
[189 159 159 188 197 197]


## Boolean Indexing 2D array

In [70]:
import numpy as np

a = np.random.randint(1, 30, (5, 6))
print(a)

[[16 19 26 12 25 12]
 [25  4 19  1 25  8]
 [13  8 20 21  7 29]
 [13  9 29  8 24  6]
 [11  5 25 24  1 10]]


In [71]:
a > 20

array([[False, False,  True, False,  True, False],
       [ True, False, False, False,  True, False],
       [False, False, False,  True, False,  True],
       [False, False,  True, False,  True, False],
       [False, False,  True,  True, False, False]])

In [74]:
bool_arr = a > 20
ans = a[bool_arr]
print(ans)

[26 25 25 25 21 29 29 24 25 24]


In [76]:
b = a
print(a)
b[bool_arr] = -1
print(b)

[[ 16  19 100  12 100  12]
 [100   4  19   1 100   8]
 [ 13   8  20 100   7 100]
 [ 13   9 100   8 100   6]
 [ 11   5 100 100   1  10]]
[[16 19 -1 12 -1 12]
 [-1  4 19  1 -1  8]
 [13  8 20 -1  7 -1]
 [13  9 -1  8 -1  6]
 [11  5 -1 -1  1 10]]


In [77]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[6 5]
 [6 6]]


In [79]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [80]:
print(c[ c_bool ])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [84]:
b = np.random.randint(1, 30, (5, 6))
print(b)

[[ 4 21 26 10 12 14]
 [25 19 10 27 11  1]
 [16 25 16 20 27  3]
 [29 20  7 29 25 17]
 [ 8 24 11 20 14 25]]


In [85]:
bool_arr = b[:, 3] == 20
print(bool_arr)

[False False  True False  True]


In [86]:
b[bool_arr, 3] = -9
print(b)

[[ 4 21 26 10 12 14]
 [25 19 10 27 11  1]
 [16 25 16 -9 27  3]
 [29 20  7 29 25 17]
 [ 8 24 11 -9 14 25]]


In [87]:
b = np.array([[21, 20, 19, 18, 17], [16, 15, 14, 13, 12], [11, 10, 9, 8, 7], [6, 5, 4, 3, 2]])
print(b)
c = b[b[:,1].argsort()]
print(c)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
