### Treat Mathematical Operations on unequal size of matrix

In [1]:
import numpy as np

x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print(x)
print(y)

[[6 6 9]
 [3 3 1]
 [2 9 6]]
[[4 7 2]
 [6 9 4]
 [2 6 2]]


In [2]:
x-y

array([[ 2, -1,  7],
       [-3, -6, -3],
       [ 0,  3,  4]])

In [3]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3))

print(x)
print(y)

[[5 8 2]
 [8 5 6]
 [8 5 2]]
[8 5 9]


In [4]:
x - y

array([[-3,  3, -7],
       [ 0,  0, -3],
       [ 0,  0, -7]])

In [5]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))

print(x)
print(y)

[[2 6]
 [6 8]
 [7 4]]
[[2 8 1]
 [5 7 1]]


In [7]:
x - y

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [8]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[2 5]
 [8 7]
 [1 1]]
[[ 0  1]
 [-2  1]
 [ 6  3]]


### np.resize() np.reshape(array, shape, order = 'C')

In [11]:
## Change by reshape() is temporary
a = np.arange(10)
print(a)
print( a.reshape(2, 5))
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
## Change by resize() is permanently
a = np.arange(10)
print(a)
a.resize(2, 5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
b = np.arange(6)
print(b)
c = b.reshape(3, 5)
print(c)

[0 1 2 3 4 5]


ValueError: cannot reshape array of size 6 into shape (3,5)

In [20]:
## resize() append zeros in end if shape is incompatible
b = np.arange(6)
print(b)
b.resize(3, 5)
print(b)

[0 1 2 3 4 5]
[[0 1 2 3 4]
 [5 0 0 0 0]
 [0 0 0 0 0]]
