In [1]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


### NumPy array is homogenous (contain same type element)

In [3]:
 a = [1, 2, 3, 'a', '4', 4.5]
 b = np.array(a)
 print(b) 
 ## By  default numpy create homogenous array of type string if list contain diff type elements.

['1' '2' '3' 'a' '4' '4.5']


### np.array(list, dtype = any_data_type) 
#### dtype = int/float...

In [5]:
 ## 'a'  can't convert into int
 a = [1, 2, 3, 'a', '4', 4.5]
 b = np.array(a, dtype = int)
 print(b) 

ValueError: invalid literal for int() with base 10: 'a'

In [19]:
 ## convert into int
 a = [1, 2, 3, '4', 4.5]
 b = np.array(a, dtype = int)
 print(b) 

[1 2 3 4 4]


In [22]:
 ## Convert into float
 a = [1, 2, 3, '4', 4.5]
 b = np.array(a, dtype = float)
 print(b) 

[1.  2.  3.  4.  4.5]


In [24]:
 ## Convert into string
 a = [1, 2, 3, '4', 4.5]
 b = np.array(a, dtype = str)
 print(b) 

['1' '2' '3' '4' '4.5']


In [25]:
 a = [1, 2, 3, '4', 4.5]
 b = np.array(a*3, dtype = int)
 print(b) 

[1 2 3 4 4 1 2 3 4 4 1 2 3 4 4]


In [26]:
## By default element type is float
b = np.ones(3)
b

array([1., 1., 1.])

In [27]:
b = np.ones(3, dtype=int)
b

array([1, 1, 1])

In [28]:
## By default element type is float
b = np.zeros(3)
b

array([0., 0., 0.])

In [29]:
b = np.zeros(3, dtype=int)
b

array([0, 0, 0])

### Create 2d array of 0's and 1's using np.ones((row,col)) and np.zeroes((row,col))

In [30]:
b = np.ones((2,3), dtype= int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
b = np.zeros((4,3), dtype= float)
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### np.fill(size , value, dtype)

In [33]:
b = np.full(3, 5)
b

array([5, 5, 5])

In [35]:
b = np.full((3,5), 6, dtype= float)
b

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

### np.empty(shape, dtype=float)    order : C_contiguous or F_contiguous
#### empty() used to create array of given shape with random values

In [37]:
b = np.empty(3, dtype=int)
b

array([94329267546012,              0,             32])

In [42]:
b = np.empty([2,3], dtype=float)
b

array([[4.66048503e-310, 0.00000000e+000, 6.91632716e-310],
       [6.91634317e-310, 6.91634317e-310, 6.91632718e-310]])

In [43]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a, dtype=int)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
b = np.zeros(10, dtype=int)
b[4] = 1
print(b)

[0 0 0 0 1 0 0 0 0 0]


### print any random value

In [45]:
np.random.rand()

0.9907263833972881

### np.arange(start=0, stop, step=1, dtype)

In [46]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

### np.linspace( start, stop, num=50, endpoint=True, retstep=false, dtype=None, axis=0)

In [51]:
b = np.linspace(2,10)
b
print("step vallue")
print(b[1]-b[0])
print(b[3] - b[2])

step vallue
0.16326530612244916
0.16326530612244916


In [52]:
b = np.linspace(2,10,5)
b

array([ 2.,  4.,  6.,  8., 10.])

In [53]:
b = np.linspace(2,10,5, dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [55]:
b = np.linspace(2,10,5, dtype=int, endpoint=False)
b

array([2, 3, 5, 6, 8])

### np.identity()   Returnn only square identity matrix

In [56]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.eye()     Capable of return rectangle identity matrix

In [58]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.random.rand()  create array of random from range 0 to 10

In [60]:
b = np.random.rand()
b

0.6557990789592045

In [61]:
b = np.random.rand(3)
b

array([0.29453182, 0.49276604, 0.27701306])

In [62]:
b = np.random.rand(2,3)
b

array([[0.75601254, 0.85637804, 0.51684908],
       [0.58218638, 0.60253199, 0.13659915]])

In [64]:
## print  random value from 0 to 10
b = np.random.rand(10)*10
b

array([6.3086323 , 6.84373695, 7.15937313, 1.48382359, 2.25261208,
       0.95113056, 9.25253561, 2.78781472, 6.0626784 , 4.12120706])

In [68]:
# Print random integer value from 0 to given range
b = np.random.randint(1000)
b

689

In [71]:
b = np.random.randint(10, size=(4))
b

array([1, 3, 7, 0])

In [72]:
b = np.random.randint(10, size=(4,6))
b

array([[0, 9, 6, 3, 9, 3],
       [9, 8, 1, 2, 9, 0],
       [1, 1, 9, 7, 3, 5],
       [4, 0, 6, 3, 5, 0]])

In [73]:
b = np.arange(9,49)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48])

In [79]:
b = np.arange(9,49+1)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [77]:
b = np.linspace(9,49,(49-9+1), dtype=int)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [80]:
c = np.eye(5,6)
c

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [84]:
## cut the rope of 5m into 9  equal parts
b = np.linspace(0,5,9)
b

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])