In [2]:
import numpy as np

### 1D Array

In [4]:
li = [1,2,3,4,5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


### 2D Array

In [5]:
li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### data, shape, dtype, strides

In [6]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


In [7]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


### 1D Array Indexing and Slicing

In [12]:
li = [1,2,3,4,5]
arr = np.array(li)

print(li[3])
print(arr[3])

4
4


In [11]:
print(li[1:4])
print(arr[1:4])

[2, 3, 4]
[2 3 4]


### 2D Array Indexing and Slicing

In [13]:
li_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
arr_2d = np.array(li_2d)

In [16]:
## Indexing
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

10
10
10


In [18]:
print(li_2d[1][:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]


In [23]:
print(li_2d[:3][2])

[9, 10, 11, 12]


In [24]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [27]:
print(li_2d[:3][3])

IndexError: list index out of range

In [25]:
print(arr_2d[0:3, 2])

[ 3  7 11]


In [26]:
print(arr_2d[0:3][2])

[ 9 10 11 12]


In [31]:
print(arr_2d)
print(arr_2d[2:4, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[10 11]
 [14 15]]


In [30]:
print(arr_2d)
print(arr_2d[2:3, :3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11]]


In [32]:
print(arr_2d[1:4, 3:])

[[ 8]
 [12]
 [16]]


In [33]:
print(arr_2d[2:4, :4])

[[ 9 10 11 12]
 [13 14 15 16]]


In [34]:
print(arr_2d[1:3, 1:3])

[[ 6  7]
 [10 11]]
