### random.randint(start, end, size)

In [1]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[12  3  6  7 14]
[13  4  1 18 18]


In [2]:
li = [i+1 for i in li]
print(li)

[2, 3, 4, 5, 6]


In [3]:
a = a + 1
a

array([13,  4,  7,  8, 15])

In [4]:
c = a + b
c

array([26,  8,  8, 26, 33])

In [6]:
d = a - b
d

array([  0,   0,   6, -10,  -3])

In [8]:
m = a * b
m

array([169,  16,   7, 144, 270])

In [9]:
f = a / b
f

array([1.        , 1.        , 7.        , 0.44444444, 0.83333333])

In [10]:
g = a // b
g

array([1, 1, 7, 0, 0])

In [11]:
h = a ** b
h

array([    302875106592253,                 256,                   7,
         18014398509481984, 2152354138636261345])

In [12]:
print(a)
print('sum ', a.sum())
print('average ', a.mean())
print('min ', a.min())
print('index of min element ', a.argmin())
print('max ', a.max())
print('index of max element ', a.argmax())

[13  4  7  8 15]
sum  47
average  9.4
min  4
index of min element  1
max  15
index of max element  4


### Logical and Relational Operations

In [13]:
print(a)
print(b)

[13  4  7  8 15]
[13  4  1 18 18]


In [14]:
a > b

array([False, False,  True, False, False])

In [15]:
b > a

array([False, False, False,  True,  True])

In [17]:
a == b

array([ True,  True, False, False, False])

In [18]:
a <= b 

array([ True,  True, False,  True,  True])

In [19]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [20]:
print(np.logical_not(a))
print(np.logical_not(b))

[False False False False False]
[False False False False False]


In [21]:
a[2] = 0
print(np.logical_not(a))

[False False  True False False]
